/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author tibd8
 */
public class tela extends javax.swing.JFrame {
    float numero =0;
    int operador =0;

    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        btum = new javax.swing.JButton();
        btdois = new javax.swing.JButton();
        bttres = new javax.swing.JButton();
        btsoma = new javax.swing.JButton();
        btcinco = new javax.swing.JButton();
        btseis = new javax.swing.JButton();
        btquatro = new javax.swing.JButton();
        btsubtracao = new javax.swing.JButton();
        btoito = new javax.swing.JButton();
        btnove = new javax.swing.JButton();
        btsete = new javax.swing.JButton();
        btdivisao = new javax.swing.JButton();
        btzero = new javax.swing.JButton();
        btmultiplicacao = new javax.swing.JButton();
        btlimpar = new javax.swing.JButton();
        btigual = new javax.swing.JButton();
        c = new javax.swing.JButton();
        btvirgula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btum.setText("1");
        btum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btumMouseClicked(evt);
            }
        });

        btdois.setText("2");
        btdois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btdoisMouseClicked(evt);
            }
        });

        bttres.setText("3");
        bttres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttresMouseClicked(evt);
            }
        });

        btsoma.setText("+");
        btsoma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsomaMouseClicked(evt);
            }
        });

        btcinco.setText("5");
        btcinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcincoMouseClicked(evt);
            }
        });
        btcinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcincoActionPerformed(evt);
            }
        });

        btseis.setText("6");
        btseis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btseisMouseClicked(evt);
            }
        });

        btquatro.setText("4");
        btquatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btquatroMouseClicked(evt);
            }
        });

        btsubtracao.setText("-");
        btsubtracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsubtracaoMouseClicked(evt);
            }
        });

        btoito.setText("8");
        btoito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoitoMouseClicked(evt);
            }
        });

        btnove.setText("9");
        btnove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnoveMouseClicked(evt);
            }
        });
        btnove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoveActionPerformed(evt);
            }
        });

        btsete.setText("7");
        btsete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btseteMouseClicked(evt);
            }
        });

        btdivisao.setText("/");
        btdivisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btdivisaoMouseClicked(evt);
            }
        });

        btzero.setText("0");
        btzero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btzeroMouseClicked(evt);
            }
        });
        btzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btzeroActionPerformed(evt);
            }
        });

        btmultiplicacao.setText("*");
        btmultiplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmultiplicacaoMouseClicked(evt);
            }
        });

        btlimpar.setText("CE");
        btlimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlimparMouseClicked(evt);
            }
        });

        btigual.setText("=");
        btigual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btigualMouseClicked(evt);
            }
        });

        c.setText("C");
        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMouseClicked(evt);
            }
        });

        btvirgula.setText(",");
        btvirgula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvirgulaMouseClicked(evt);
            }
        });
        btvirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvirgulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(display)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelLayout.createSequentialGroup()
                                    .addComponent(btum, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btdois, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bttres, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btsoma, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painelLayout.createSequentialGroup()
                                    .addComponent(btquatro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btcinco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btseis, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btsubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painelLayout.createSequentialGroup()
                                    .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(painelLayout.createSequentialGroup()
                                            .addComponent(btsete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btoito, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(painelLayout.createSequentialGroup()
                                            .addComponent(btzero, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btvirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                                            .addComponent(btlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btmultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(painelLayout.createSequentialGroup()
                                            .addComponent(btnove, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btdivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(painelLayout.createSequentialGroup()
                                .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btigual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btum)
                    .addComponent(btdois)
                    .addComponent(bttres)
                    .addComponent(btsoma))
                .addGap(12, 12, 12)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btquatro)
                    .addComponent(btcinco)
                    .addComponent(btseis)
                    .addComponent(btsubtracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsete)
                    .addComponent(btoito)
                    .addComponent(btnove)
                    .addComponent(btdivisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btzero)
                    .addComponent(btmultiplicacao)
                    .addComponent(btlimpar)
                    .addComponent(btvirgula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(btigual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btzeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btzeroActionPerformed

    private void btnoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnoveActionPerformed

    private void btcincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcincoActionPerformed

    private void btsomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsomaMouseClicked
                // TODO add your handling code here:
                numero = Float.parseFloat(display.getText());
                operador=1;
                display.setText("");
    }//GEN-LAST:event_btsomaMouseClicked

    private void btigualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btigualMouseClicked
            // TODO add your handling code here:
            if (operador==1){
                float resultado = numero + Float.parseFloat(display.getText());
                display.setText(""+ resultado);
                numero=resultado;
            }else if (operador==2){
                float resultado = numero - Float.parseFloat(display.getText());
                display.setText(""+ resultado);
                numero=resultado;
            }else if (operador==3){
                float resultado = numero / Float.parseFloat(display.getText());
                display.setText(""+ resultado);
                numero=resultado;
            }else if (operador==4){
                float resultado = numero * Float.parseFloat(display.getText());
                display.setText(""+ resultado);
                numero=resultado;
            }
    }//GEN-LAST:event_btigualMouseClicked

    private void btsubtracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsubtracaoMouseClicked
        // TODO add your handling code here:
                numero = Float.parseFloat(display.getText());
                operador=2;
                display.setText("");
    }//GEN-LAST:event_btsubtracaoMouseClicked

    private void btdivisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdivisaoMouseClicked
        // TODO add your handling code here:
                numero = Float.parseFloat(display.getText());
                operador=3;
                display.setText("");
    }//GEN-LAST:event_btdivisaoMouseClicked

    private void btmultiplicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmultiplicacaoMouseClicked
        // TODO add your handling code here:
                numero = Float.parseFloat(display.getText());
                operador=4;
                display.setText("");
    }//GEN-LAST:event_btmultiplicacaoMouseClicked

    private void btlimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlimparMouseClicked
        // TODO add your handling code here:
        String ultimo = display.getText();
        if(ultimo.length() > 0){
            display.setText(ultimo.substring(0,ultimo.length() -1));
        }
    }//GEN-LAST:event_btlimparMouseClicked

    private void btumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btumMouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "1");
    }//GEN-LAST:event_btumMouseClicked

    private void btdoisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdoisMouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "2");
    }//GEN-LAST:event_btdoisMouseClicked

    private void bttresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttresMouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "3");
    }//GEN-LAST:event_bttresMouseClicked

    private void btquatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btquatroMouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "4");
    }//GEN-LAST:event_btquatroMouseClicked

    private void btcincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcincoMouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "5");
    }//GEN-LAST:event_btcincoMouseClicked

    private void btseisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btseisMouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "6");
    }//GEN-LAST:event_btseisMouseClicked

    private void btseteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btseteMouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "7");
    }//GEN-LAST:event_btseteMouseClicked

    private void btoitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoitoMouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "8");
    }//GEN-LAST:event_btoitoMouseClicked

    private void btnoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnoveMouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "9");
    }//GEN-LAST:event_btnoveMouseClicked

    private void btzeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btzeroMouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "0");
    }//GEN-LAST:event_btzeroMouseClicked

    private void cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseClicked
        display.setText("");
    }//GEN-LAST:event_cMouseClicked

    private void btvirgulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvirgulaMouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + ",");
    }//GEN-LAST:event_btvirgulaMouseClicked

    private void btvirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvirgulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btvirgulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcinco;
    private javax.swing.JButton btdivisao;
    private javax.swing.JButton btdois;
    private javax.swing.JButton btigual;
    private javax.swing.JButton btlimpar;
    private javax.swing.JButton btmultiplicacao;
    private javax.swing.JButton btnove;
    private javax.swing.JButton btoito;
    private javax.swing.JButton btquatro;
    private javax.swing.JButton btseis;
    private javax.swing.JButton btsete;
    private javax.swing.JButton btsoma;
    private javax.swing.JButton btsubtracao;
    private javax.swing.JButton bttres;
    private javax.swing.JButton btum;
    private javax.swing.JButton btvirgula;
    private javax.swing.JButton btzero;
    private javax.swing.JButton c;
    private javax.swing.JTextField display;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}
